const finishingMessages = [
    "Well done! Hope it tastes amazing.",
    "You did it! Time to dig in.",
    "Nice work, chef!",
    "Mission accomplished. Enjoy your creation!",
    "Another one cooked to perfection.",
    "Boom! That’s how it’s done.",
    "Cheers to your masterpiece!",
    "You’ve earned this bite.",
    "Deliciousness awaits. Well played.",
    "You crushed it!",
    "Recipe complete. You’re a natural.",
    "Well cooked, well deserved.",
    "Take a bow, chef.",
    "Yum! Let’s eat.",
    "That smells like success.",
    "That’s a wrap — serve it up!",
    "Bravo! You cooked like a pro.",
    "From prep to plate — nailed it.",
    "Your kitchen skills are 🔥",
    "Plate it up and flex.",
    "Tastebuds will thank you.",
    "You mastered this recipe!",
    "You brought it to life!",
    "One more recipe under your belt.",
    "Savor the results!",
    "Culinary achievement unlocked.",
    "Enjoy every bite — you earned it.",
    "Cooking complete. Victory tastes good.",
    "Forks up!",
    "Dinner’s ready — and it looks amazing.",
    "That’s some top-tier cooking!",
    "Skill level: rising.",
    "Looks restaurant-worthy!",
    "You made magic in the kitchen.",
    "Gold star for the chef ⭐",
    "Clean apron, full stomach, can’t lose.",
    "Ready to serve — great job!",
    "That’s a flavor win.",
    "Well seasoned, well executed.",
    "From scratch to snack — nailed it!"
  ];

  export default finishingMessages;